# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy HTML to Azure Web App - EduardoSite123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_534A02192C974457A57D09021FDD63BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C38CB32E0431409F80A53CA85FE9BD72 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_622723040814464788EF7AA1E5468694 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EduardoSite123'
          slot-name: 'Production'
          package: .
