# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy HTML to Azure Web App - eduardosite123

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_181BF5AAAC924B19BC1D4B6787E4A8B8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0122C76BFD6D4EE495D899B75F1CFACB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2637F48AD5724B4E99DEBC4E7CC73CD5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EduardoSite123'
          slot-name: 'stagging'
          package: .
